nodeLinker: hoisted
onlyBuiltDependencies:
  - esbuild
  - "@rolldown/binding-wasm32-wasi"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
minimumReleaseAgeExclude:
  - astro@7.3.3
allowBuilds:
  esbuild: set this to true or false
